module.exports = Object.freeze({
  USER_NO_ACTIVE: "USER_NO_ACTIVE",
  PROFILE_NO_ACTIVE: "PROFILE_NO_ACTIVE",
  CLIENT_NO_ACTIVE: "CLIENT_NO_ACTIVE",
  ERROR_NO_UPDATED: "ERROR_NO_UPDATED",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  WRONG_DATA: "WRONG_DATA",
  ERROR_FORM: "ERROR_FORM",
});
