module.exports = Object.freeze({
  NO_ACTIVE: "NO_ACTIVE",
  USER_NO_ACTIVE: "USER_NO_ACTIVE",
  PROFILE_NO_ACTIVE: "PROFILE_NO_ACTIVE",
  CLIENT_NO_ACTIVE: "CLIENT_NO_ACTIVE",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  EMAIL_ERROR: "EMAIL_ERROR",
  EXPIRED_SUBSCRIPTION: "EXPIRED_SUBSCRIPTION",
  NO_KEY_CLIENT: "NO_KEY_CLIENT",
  UNDEFINED_KEY_CLIENT: "UNDEFINED_KEY_CLIENT",
  WRONG_KEY_CLIENT: "WRONG_KEY_CLIENT",
});
