version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - cp package.json build/
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
